### ISSUE TITLE
Linode Instance Imported with root_device of "/dev/root"

### ISSUE THREAD

**Issue by andystevensname** [terraform-providers/terraform-provider-linode#10]
### Terraform Version
Terraform v0.11.10
+ provider.linode v1.0.0

### Affected Resource(s)
- linode\_instance

### Terraform Configuration Files
```hcl
provider "linode" {
    token = "${var.token}"
}

resource "linode_instance" "terraform-import" {
    label = "terraform-import"
    group = "Terraform"
    region = "us-east"
    type = "g6-standard-1"
    config {
        label = "My Debian 9 Disk Profile"
        kernel = "linode/grub2"
        root_device = "/dev/sda"
        devices {
            sda = {
                disk_label = "Debian 9 Disk"
            }
            sdb = {
                disk_label = "512 MB Swap Image"
            }
        }
    }
    disk {
        label = "Debian 9 Disk"
        size = 50688
    }
    disk {
        label = "512 MB Swap Image"
        size = 512
    }
}
```

### Expected Behavior
When importing a Linode instance, it is required to set the `root_device` in the config block so that the correct disk is targeted as the root device. Inclusion of this setting, and all other required settings for an import, should result in a clean `terraform plan`.

### Actual Behavior
The Linode instance is imported with the `root_device` set to `/dev/root` regardless of the setting. This results the following `terraform plan`:

```
  ~ linode_instance.terraform-import
      config.0.root_device: "/dev/root" => "/dev/sda"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a Linode resource block based on an existing Linode.
2. `terraform import linode_instance.<instance_label> <instance_id>`
3. `terraform plan`

### Important Factoids
This is more of an annoyance, as it does not seem to affect the Linode upon `terraform apply`, ie, the correct disk would be applied anyway if it worked.

**Comment by dobromyslov** [comment]
This is very annoying.

**Comment by nZac** [comment]
I dug into this a bit because we ran into the issue. The problem is here: https://github.com/terraform-providers/terraform-provider-linode/blob/master/linode/linode_instance_helpers.go#L133-L143

To workaround the issue I just moved my boot disk to `/dev/sdb` and my swap disk to `/dev/sda` then set my `root_device=/dev/sdb`.
