### ISSUE TITLE
Linode instance downsize doesn't work

### ISSUE THREAD

**Issue by liejuntao001** [terraform-providers/terraform-provider-linode#13]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.11.8
+ provider.linode v1.3.0
+ provider.null v1.0.0
+ provider.random v2.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- linode\_instance

modify instance type from
"g6-standard-1" to
"g6-nanode-1"

log:

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.newtest.linode_instance.linode-template: Modifying... (ID: 11668149)
  config.0.root_device: "/dev/root" => "/dev/sda"
  disk.1.size:          "43008" => "17408"
  type:                 "g6-standard-1" => "g6-nanode-1"

Error: Error applying plan:

1 error(s) occurred:

* module.newtest.linode_instance.linode-template: 1 error(s) occurred:

* linode_instance.linode-template: Error resizing instance 11668149: [400] Linode has allocated more disk than the new service plan allows. Delete or resize disks smaller.

### Expected Behavior
the instance get down sized

### Actual Behavior
failed to do so

**Comment by displague** [comment]
It sounds like the expected behavior here is that the disk size changes should be applied before the instance resize.

**Comment by displague** [comment]
https://github.com/terraform-providers/terraform-provider-linode/blob/b3c01af25e327e9c7ff7932951a5a8f0d9539bb8/linode/resource_linode_instance.go#L1163-L1175

The order of these two steps (resize the linode, resize the disk) should be based on the direction of the sum of disk size changes.  
- If it is a request to decrease the total disks, disk changes should come first.  
- If it is a request to increase the total disk size, the instance resize should happen first.

**Comment by displague** [comment]
Was this corrected in #55, @ellisbenjamin ?

**Comment by Charliekenney23** [comment]
Consolidating to #103
