### ISSUE TITLE
Empty "name" for A domain record

### ISSUE THREAD

**Issue by ffissore** [terraform-providers/terraform-provider-linode#140]
### Terraform Version
v0.12.23
provider.linode >= 1.9

### Affected Resource(s)
- linode\_domain\_record

### Terraform Configuration Files
```
resource "linode_domain" "jrecordbind" {
  type      = "master"
  domain    = "jrecordbind.org"
  soa_email = "info@jrecordbind.org"
}

resource "linode_domain_record" "jrecordbind_A" {
  domain_id   = linode_domain.jrecordbind.id
  name        = ""
  record_type = "A"
  target      = var.deutche_welle_ip
}
```

### Expected Behavior
Linode DNS manager allows me to create a "A" record without a "name", I expect to do the same via terraform

### Actual Behavior
Terraform reports error `Error: name is required for non-SRV records`

Suggestions/Workarounds are welcome

**Comment by Charliekenney23** [comment]
@ffissore What minor version of the provider are you on?

This was fixed in #136 which was part of the [1.9.3 release](https://github.com/terraform-providers/terraform-provider-linode/blob/master/CHANGELOG.md#193-april-17-2020).

**Comment by Charliekenney23** [comment]
@ffissore Just an FYI, your configuration works on the latest. See [here](https://gist.github.com/Charliekenney23/e1a6fec4cc3b892293665e86de936081).

**Comment by ffissore** [comment]
@Charliekenney23 I confirm it works with 1.9.3. I don't know which version I had but surely it was older. Changed my `provider` like so
```
provider "linode" {
  version = ">= 1.9.3"
  token   = var.linode_token
}
```
re-run `terraform init` and then applied successfully. Thank you!
