### ISSUE TITLE
Incorrect release tag?

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-linode#163]
The release tags have gone from 1.11.2 to 1.12.3 - was this an incorrect tag?

If so, this would be a useful thing to point out in the CHANGELOG as to make sure others are not confused :D

**Comment by Charliekenney23** [comment]
@stack72 Yes this is a release error, please hold out on pulling into Pulumi. Discussing with HashiCorp now the best way to revert and re-release as 1.11.3.

I'll update here when I have more.

**Comment by stack72** [comment]
Thanks @Charliekenney23!

**Comment by Charliekenney23** [comment]
@stack72 We decided rather than reverting, it makes more sense to just roll with the versioning and add a disclaimer, as to not cause checksum conflicts with future releases.

**Comment by stack72** [comment]
Makes sense to me! I will ensure we do something similar
