### ISSUE TITLE
Linode instance upsize with disk expansion at same time doesn't work

### ISSUE THREAD

**Issue by liejuntao001** [terraform-providers/terraform-provider-linode#17]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.8
+ provider.linode v1.3.0
+ provider.null v1.0.0
+ provider.random v2.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- linode\_instance

### Terraform Configuration Files
I'm doing upsize for one instance, and the disk size expand at the same time.

### Debug Output
  ~ module.newtest.linode_instance.bare
      config.0.root_device: "/dev/root" => "/dev/sda"
      disk.1.size:          "17408" => "43008"
      type:                 "g6-nanode-1" => "g6-standard-1"

module.newtest-workers.linode_instance.bare: Modifying... (ID: 11904746)
  config.0.root_device: "/dev/root" => "/dev/sda"
module.cluster1-workers.linode_instance.bare[1]: Modifications complete after 1s (ID: 11763152)
module.cluster1-workers.linode_instance.bare[0]: Modifications complete after 1s (ID: 11763151)
module.cluster1-master.linode_instance.bare: Modifications complete after 1s (ID: 11763148)
module.newtest-workers.linode_instance.bare: Modifications complete after 1s (ID: 11904746)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 10s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 20s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 30s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 40s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 50s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 1m0s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 1m10s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 1m20s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 1m30s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 1m40s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 1m50s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 2m0s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 2m10s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 2m20s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 2m30s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 2m40s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 2m50s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 3m0s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 3m10s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 3m20s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 3m30s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 3m40s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 3m50s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 4m0s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 4m10s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 4m20s elapsed)
module.newtest.linode_instance.bare: Still modifying... (ID: 11904745, 4m30s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* module.newtest.linode_instance.bare: 1 error(s) occurred:

* linode_instance.bare: Error resizing Disk 25076234: size exceeds disk size for Instance 11904745

### Expected Behavior
The instance shall upsize first, then based on the new disk cap, allow the disk expansion.

### Actual Behavior
First "terraform apply", the instance is upsized, then the apply failed.
I have to a 2nd time apply to make the disk expansion work.

**Comment by displague** [comment]
Was this corrected in #55, @ellisbenjamin ?

**Comment by Charliekenney23** [comment]
Consolidating to #103

**Comment by Charliekenney23** [comment]
This was resolve in #119
