### ISSUE TITLE
terraform always report change "/dev/root" => "/dev/sda"

### ISSUE THREAD

**Issue by liejuntao001** [terraform-providers/terraform-provider-linode#18]
### Terraform Version
Terraform v0.11.8
+ provider.linode v1.3.0
+ provider.null v1.0.0
+ provider.random v2.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- linode\_instance

### Terraform Configuration Files
resource "linode_instance" "bare" {
...
  config {
    label  = "boot_config"
    kernel = "linode/grub2"

    devices {
      sda = {
        disk_label = "root"
      }

      sdb = {
        disk_label = "data"
      }
    }

    root_device = "/dev/sda"
  }
}
### Debug Output
terraform plan
Terraform will perform the following actions:

  ~ module.cluster1-master.linode_instance.bare
      config.0.root_device: "/dev/root" => "/dev/sda"

  ~ module.cluster1-workers.linode_instance.bare[0]
      config.0.root_device: "/dev/root" => "/dev/sda"

  ~ module.cluster1-workers.linode_instance.bare[1]
      config.0.root_device: "/dev/root" => "/dev/sda"

  ~ module.newtest-workers.linode_instance.bare
      config.0.root_device: "/dev/root" => "/dev/sda"

  ~ module.newtest.linode_instance.bare
      config.0.root_device: "/dev/root" => "/dev/sda"

### Expected Behavior
Apply the said actions.

### Actual Behavior
The actions are always there, no matter how many time they are applied.
It's just annoying. Instances work as expected.

**Comment by displague** [comment]
Thank you for the detailed report, @liejuntao001!

This is also reported on #10
