### ISSUE TITLE
Unable to pass an ssh file value as an authorized key due to multi-line key

### ISSUE THREAD

**Issue by egee-irl** [terraform-providers/terraform-provider-linode#19]
Using the built-in Terraform [file](https://www.terraform.io/docs/configuration/interpolation.html#file-path-) function, an operator can retrieve the value of an SSH key and pass it into a variable or resource as a string. For whatever reason, Terraform appears to add a newline (\n) at the end of the retrieved string.

The `linode_instance` resource does not allow multi-lined ssh-keys so the additional \n at the end of the retrieved key causes the resource creation to fail.

I build AWS infrastructure using this pattern and the AWS resources can create key-pairs using Terraform's file function. The linode_instance should be able to do the same as hardcoding ssh keys in code is typically a bad pattern.

### Terraform Version
Terraform v0.11.10
+ provider.linode v1.2.0

### Affected Resource(s)
- linode\_instance

### Terraform Configuration Files
```hcl
variable "pub_key" {
  default     = "../files/id_rsa.pub"
}

resource "linode_instance" "instance" {
  image           = "linode/ubuntu18.04"
  region          = "us-central"
  type            = "g6-nanode-1"
  authorized_keys = ["${var.pub_key}"]
}
```

### Expected Behavior
The linode_instance resource can use the ssh_key retrieved by Terraform's file function and create the Linode instance.

### Actual Behavior
Resource creation fails with the following error: `* linode_instance.instance: Error creating a Linode Instance: [400] [authorized_keys] SSH Key 1 must not be multi-lined.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Using the code I posted above
1. `terraform apply`

**Comment by displague** [comment]
@egee-irl I believe you want to do this:

```hcl
variable "pub_key_file" {
  default = "${path.module}/files/id_rsa.pub"
  // or maybe you do want ../files after the module path
}

variable "pub_key" {
  default = [ "${chomp(file(var.pub_key_file))}" ]
}
```

Essentially, the `authorized_keys` field expects a list of the actual SSH public keys, not the SSH key filename:

```ssh
ssh-rsa AAAA... marques@compy.local
```


If you actually wanted to split a file that contained several public SSH keys, like an `authorized_keys` file:

```hcl
variable "pub_keys" {
  // no array, split returns an array
  default= "${split("\n",chomp(file(var.pub_key_file)))}"
}

resource "linode_instance" "foo" {
    authorized_keys = "${var.public_keys}"
}
```

**Comment by egee-irl** [comment]
You were right, a good ole chomp fixes the whitespace.

Interestingly, replacing the hardcoded string with the contents of the file forces a new resource which could be bad news for folks wanting to move away from the hardcoded string pattern. Pretty sure that is a Terraform thing and has nothing to do with linode_instance.

Feel free to close this issue or leave it open for tracking the auto-chomping of input files :+1:

**Comment by displague** [comment]
Glad to hear that was it.  I'll close the issue but will keep auto-chomping in mind.

**Comment by displague** [comment]
And @egee-irl, I'm still looking forward to that using 'Terraform with Linode' video 🎥 🤙
