### ISSUE TITLE
Should there be a default_ssh_user attribute for the linode_image data source?

### ISSUE THREAD

**Issue by gerhard** [terraform-providers/terraform-provider-linode#21]
For the `linode/containerlinux` image, the default SSH user is `core`. It would be helpful if the `linode_image` resource exposed this so that it could be used for `connection`, e.g.:

```tf
data "linode_image" "changelog" {
  id = "linode/containerlinux"
}

# ... elided for brevity

resource "linode_volume" "db" {
  region = "${data.linode_region.changelog.id}"
  label = "db"
  size = 10
  linode_id = "${linode_instance.2019.id}"

  connection {
    user = "${linode_image.changelog.default_ssh_user}" # <--- Feature request
    host = "${linode_instance.2019.ip_address}"
  }
}
```

What do you think?

**Comment by displague** [comment]
That is a really good idea.  I've been hard-coding that sort of knowledge in where needed, `(image == "linode/containerlinux") ? "core": "root"`, but with Fedora Atomic and similar OSes, this is going to be more common and a ternary won't cut it.

Ideally, this information should be exposed by the Linode API: https://developers.linode.com/api/v4#operation/getImage and then it would only be natural for the Terraform provider to mirror what the API provides.

I think is is a good and necessary extension for Terraform purposes.  

I'll raise the topic with the API team to see if I can get support added there.  In the meanwhile, I agreed that a surrogate field derived from a `core if image.id = linux/containerlinux` piece of logic would be helpful.

**Comment by bbiggerr** [comment]
This has been added as an API feature request on Linode's internal tracker. From there, we'll vet and scope the request for development. You can also submit requests to feedback@linode.com. Thanks!
