### ISSUE TITLE
Three character tag names are not allowed

### ISSUE THREAD

**Issue by mcg** [terraform-providers/terraform-provider-linode#32]
### Terraform Version
```
Terraform v0.11.10
+ provider.aws v1.59.0
+ provider.linode v1.5.0
+ provider.null v2.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- linode\_instance

### Terraform Configuration Files
```hcl
 tags = ["dev", "appserver"]
```

### Expected Behavior
Instance should be created with a 3 character tag. Or the error is incorrect and 4 character tag names are the actual limit.

### Actual Behavior
`Error creating a Linode Instance: [400] [tags[0]] Tag 'dev' must be between 3 and 50 characters`
4 character tag names do work.

### Steps to Reproduce
1.  Create an terraform with a 3 character tag name on an instance.
2. `terraform apply`

**Comment by displague** [comment]
Thanks for the detailed report, @mcg!

Coincidentally, the API team addressed this issue internally and the fix should be included in the next release (expected early next week).  The details will appear in the API changelog.

https://developers.linode.com/changelog/api/

**Comment by displague** [comment]
@mcg This bug was fixed in the API release earlier this week.
