### ISSUE TITLE
Changing Image in Disks config section of instances does not cause a resource destruction

### ISSUE THREAD

**Issue by dave-lew99** [terraform-providers/terraform-provider-linode#37]
Hi there,

I've found that when specifying an image for a Linode instance via the disks config section of an instance, changing the image parameter does not cause the resource to be recreated (indeed, it doesn't cause anything to happen).

### Terraform Version
Terraform v0.11.13
+ provider.aws v2.4.0
+ provider.linode v1.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
- linode\_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "linode_instance" "li_instance" {
    label               = "my-test-instance"
    region             = "us-central"
    type               = "g6-nanode-1"

    lifecycle {
        create_before_destroy = false
    }

  disk {
    label = "boot"
    size = 10000
    image  = "linode/centos7"
  }

  config {
    label = "boot_config"
    kernel = "linode/latest-64bit"
    devices {
      sda = { disk_label = "boot" },
    }
    root_device = "/dev/sda"
  }

    boot_config_label = "boot_config"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Terraform plan and apply should destroy the existing instance and re-launch using the new image.

Output plan:
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

linode_instance.li_instance: Refreshing state... (ID: 13461897)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ linode_instance.li_instance
      config.0.root_device: "/dev/root" => "/dev/sda"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior
What actually happened?
No changes are made

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change the image configuration e.g. linode/centos7 to linode/debian9
3. Run `terraform apply`

### Important Factoids
The docs state that this should work, i have a feeling that the Linode API returns NULL for the current image so perhaps terraform can't figure out that this has changed? The image is not stored in the state file.

**Comment by displague** [comment]
It is tempting to consider implementing this as a "Disk Rebuild" instead of a Linode destroy, but that would go against Terraform life-cycle patterns.

A user may expect that new instances are created before the old instances are destroyed, and an image update designed as a "Rebuild Disk" would not fulfill that expectation.  Instead the instance would be down while the disk is rebuilt.

I agree that a disk image change should trigger an instance destroy.

This may be easier to acomadate in Terraform 0.12 as the disks can be true sub-resources instead of a map keyed on the disk label.
