### ISSUE TITLE
Adapt to new Linode Resize behavior

### ISSUE THREAD

**Issue by displague** [terraform-providers/terraform-provider-linode#42]
Resized Linodes now automatically resize the disk/filesystem to the full size of the disk under specific conditions (1 disk with up to 1 additional swap disk).

One of the tests is failing because of this change in behavior:

https://github.com/terraform-providers/terraform-provider-linode/blob/master/linode/resource_linode_instance_test.go#L676

Users may find that a change in the Instance type to a larger plan followed by a change to a smaller plan may fail.  With the new behavior, the disk has been enlarged and is too large to be reduced back into the smaller plan.

The provider can address this by first attempting to reduce the size of disks before attempting to resize the instance.

In the case of an Instance with "disks" and "configs", changing the disk size should be left to the user and would require that https://github.com/terraform-providers/terraform-provider-linode/issues/13 be resolved.

In the case of an Instance using the "simple" configuration (no "disks" or "configs") the provider should attempt to resize the first disk by the disk size difference between the source and target instance types.

**Comment by ellisbenjamin** [comment]
This has been resolved in PR 55:

https://github.com/terraform-providers/terraform-provider-linode/blob/master/linode/resource_linode_instance.go#L1170
