### ISSUE TITLE
Linode nodebalancer documentation example bug

### ISSUE THREAD

**Issue by atleta** [terraform-providers/terraform-provider-linode#45]
Hi,

the example on the https://www.terraform.io/docs/providers/linode/r/nodebalancer_node.html doesn't work with terraform 0.11.3 and linode provider version 1.6

Using that format I get the following error:
```
* linode_nodebalancer_node.web_nodes_https: At column 1, line 1: output of an HIL expression must be a string, or a single list (argument 1 is TypeList) in:

${linode_instance.web.*.private_ip_address}:80
```

### Terraform Version
```
Terraform v0.11.11
+ provider.dme v0.1.0
+ provider.linode v1.6.0
```

### Affected Resource(s)
- linode\_nodebalancer\_node

### Terraform Configuration Files
https://www.terraform.io/docs/providers/linode/r/nodebalancer_node.html

### Important Factoids
Linode(.com) has actually a working example, see: https://www.linode.com/docs/applications/configuration-management/create-a-nodebalancer-with-terraform/ .

**Comment by atleta** [comment]
I can't seem to edit the above, but here is a bit of more context. The example in the documentation uses the following format to specify the address (without using a count): `address = "${linode_instance.web.*.private_ip_address}:80"` while the example over at Linode uses a count + the `element` built-in function and that seems to be accepted/working:
```
resource "linode_nodebalancer_node" "example-nodebalancer-node" {
    count = "${var.node_count}"
    nodebalancer_id = "${linode_nodebalancer.example-nodebalancer.id}"
    config_id = "${linode_nodebalancer_config.example-nodebalancer-config.id}"
    label = "example-node-${count.index + 1}"
    address = "${element(linode_instance.example-instance.*.private_ip_address, count.index)}:80"
    mode = "accept"
}
```

**Comment by displague** [comment]
Thanks @atleta!  That's definitely a documentation bug and your suggestion is correct.

Feel free to create the pull request: 

https://github.com/terraform-providers/terraform-provider-linode/edit/master/website/docs/r/nodebalancer_node.html.md

Otherwise, I'll pick this up in the next release.

**Comment by atleta** [comment]
OK, I'll look into it in a few days.
