### ISSUE TITLE
swap_size is ignored when resizing a linode

### ISSUE THREAD

**Issue by atleta** [terraform-providers/terraform-provider-linode#46]
Hi there,

`swap_size` is ignored when resizing (enlarging) a linode, even though the plan shows that it would be increased. This is probably related to #42 and can be mitigated at once. If the linode resizing behaviour does honour it then the implementation *when enlarging an instance* should be trivial. (It may disregard it, though, which may be the cause of this behaviour.)

### Terraform Version
```Terraform v0.11.11
+ provider.linode v1.6.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- linode\_instance

### Expected Behavior
Increasing the swap size while also selecting a larger instance size should result in having the new swap size after the resize operation with the disk expanding to the remaining free space (i.e. what remains with the larger, new swap).

### Actual Behavior
swap size remains unchanged.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Never switched to metered billing? Have beta or restricted privileges?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by atleta** [comment]
Hm... looking at their API, this doesn't seem to be doable without first resizing (enlarging) the instance and thus the disk (root file system) and then downsizing it and enlarging the swap area.

**Comment by atleta** [comment]
Hm... looking at their API, this doesn't seem to be doable without first resizing (enlarging) the instance and thus the disk (root file system) and then downsizing it and enlarging the swap area. Which is a viable strategy to changing the swap size by itself. Nevertheless, if the swap size can be changed, then it should be acted upon and not be silently ignored.

**Comment by displague** [comment]
This may have been addressed by #55. What do you think, @ellisbenjamin?
