### ISSUE TITLE
config helper docs on terraform.io do not render in the correct depth

### ISSUE THREAD

**Issue by displague** [terraform-providers/terraform-provider-linode#47]
The [Linode Instance Config docs on terraform.io](https://www.terraform.io/docs/providers/linode/r/instance.html#configs) don't reflect the formatting and extra indentation level on config.helpers.. 

Compare with this: https://github.com/terraform-providers/terraform-provider-linode/blob/master/website/docs/r/instance.html.md#configs

A user may be confused by this and assume:

```hcl
  config {
    label = "boot_config"
    kernel = "linode/direct-disk"
    network = false
  }
```

Rather than:

```hcl
  config {
    label = "boot_config"
    kernel = "linode/direct-disk"
    helper {
        network = false
    }
  }
```

**Comment by Charliekenney23** [comment]
The indentation is there now and it is easy to see that `helper` is a nested attribute. See: https://github.com/terraform-providers/terraform-provider-linode/blob/master/website/docs/r/instance.html.md#configs
