### ISSUE TITLE
not compatible with Terraform 0.12

### ISSUE THREAD

**Issue by david187** [terraform-providers/terraform-provider-linode#50]
### Terraform Version
Terraform v0.11.14
+ provider.linode v1.6.0

### Debug Output
terraform 0.12checklist 
After analyzing this configuration and working directory, we have identified some necessary steps that we recommend you take before upgrading to Terraform v0.12:

- [ ] Upgrade provider "linode" to a version that is compatible with Terraform 0.12.
  
  No compatible version is available for automatic installation at this time. If this provider is still supported (not archived) then a compatible release should be available soon. For more information, check for 0.12 compatibility tasks in the provider's issue tracker.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform 0.12checklist 

=============
### Terraform Version
Terraform v0.12.0
+ provider.linode v1.6.0

### Debug Output
terraform_ init --upgrade

No available provider "linode" plugins are compatible with this Terraform version.

From time to time, new Terraform major releases can change the requirements for
plugins such that older plugins become incompatible.

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Unfortunately, none of the suitable versions are compatible with this version
of Terraform. If you have recently upgraded Terraform, it may be necessary to
move to a newer major release of this provider. Alternatively, if you are
attempting to upgrade the provider to a new major version you may need to
also upgrade Terraform to support the new version.

Consult the documentation for this provider for more information on
compatibility between provider versions and Terraform versions.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform_ init --upgrade

**Comment by thapakazi** [comment]
Any updates on this ??
I stumbled upon the same.
Just did a downgrade to `terraform    0.11.13`  from ~Terraform v0.12.1~

**Comment by codestorm1** [comment]
II'm also looking for that update

**Comment by ellisbenjamin** [comment]
Hey there folks. We've released v1.7.0 of the Linode TF provider, and it is compatible with TF 0.12. Current releases of TF should automatically download the provider and work right away.
