### ISSUE TITLE
Private Images Do Not Allow Configuration of Multiple Disks

### ISSUE THREAD

**Issue by kellinm** [terraform-providers/terraform-provider-linode#61]
### Terraform Version
2019/10/23 13:47:24 [INFO] Terraform version: 0.12.12
2019/10/23 13:47:24 [DEBUG] found provider "terraform-provider-linode_v1.8.0_x4"

### Affected Resource(s)

- linode\_instance

### Terraform Configuration Files
```hcl
provider "linode" {
  token = "${var.linode_token}"
}

resource "linode_instance" "tf_example" {
  label = "tf_example"
  region = "${var.region}"
  type = "g6-nanode-1"
  group = "test"
  tags = ["test"]

  config {
    label = "main_boot"
    kernel = "linode/latest-64bit"
    root_device = "/dev/sda"

    devices {
      sda {
        disk_label = "boot"
      }
      sdb {
        disk_label = "Swap Image"
      }
      sdc {
        disk_label = "logs"
      }
    }
  }
  disk {
    label = "boot"
    size = "3000"
    image = "linode/centos8"
    root_pass = "${var.root_pass}"
    authorized_keys = ["${var.ssh_key}"]
  }
  disk {
    label = "Swap Image"
    filesystem = "swap"
    size = "512"
  }
  disk {
    label = "logs"
    filesystem = "ext4"
    size = "10000"
  }

  boot_config_label = "main_boot"
}

variable "linode_token" {}
variable "root_pass" {}
variable "ssh_key" {}
variable "region" {
  default = "us-central"
}
```

### Debug Output

https://gist.github.com/kellinm/5ca9ecafc58063f0b8c40f922570bdcc

### Expected Behavior
Terraform should make a linode with disks as specified and the private image as the operating system.

### Actual Behavior
If I change the image as noted above from a public one to a private one, it throws the error as shown in the gist and creates the linode, but with only the boot disk and not in a running state.

### Steps to Reproduce
1. Change the `image` field to point at a private image
1. `terraform apply`

### Important Factoids
None that I am aware of; but I will tag a support ticket with a link to this bugrep so you can check any other logs that would be useful to you.

I filed a [community forums issue earlier](https://www.linode.com/community/questions/19016/custom-image-with-terraform-and-extra-disks), but the more I look, the more I don't think it's intentional behavior.

**Comment by phillc** [comment]
You are correct, this is not the intentional behavior. The reason this happens is that the image needs to “thaw”, a state that is visible in Linode classic manager, but not currently observable from the API. We are working internally to come up with a solution.

**Comment by kellinm** [comment]
Thanks for the update!

I'll gladly help test if you need it.  Just let me know.

**Comment by kellinm** [comment]
@phillc how is it going with discussions on how to make the thaw state observable from the API?

**Comment by phillc** [comment]
@kellinm I believe the solution will be to continue to retry on that "Linode is busy" error, and I am working on trying to achieve that in our Go library.

**Comment by phillc** [comment]
@kellinm I don't know if you are able to, but as a temporary solution if you load your disk with the private image _last_ it should work.

**Comment by phillc** [comment]
Hello,

There should be a patch in the next version of our terraform provider. Let me know if this resolves your issue.

Thanks!

**Comment by kellinm** [comment]
@phillc my issue is now resolved thanks for the fix!
