### ISSUE TITLE
terraform fails if running apply twice with missing tfstate file

### ISSUE THREAD

**Issue by odra** [terraform-providers/terraform-provider-linode#64]
Running `apply` again to regenrate the tfstate file fails because it is trying to create a new `linode_instance` instance with an existing tag.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- linode\_instance

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
What should have happened?

Terraform should have skipped the instance creation itself and create the tfstate file again.

### Actual Behavior
```
Error: Error creating a Linode Instance: [400] [label] Label must be unique among your linodes
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Add a simple `linode_instance` resource;
2. Run `terraform apply`
3. Delete tfstate generated files
4. Run apply again

**Comment by phillc** [comment]
Hello,

You will need to import your state. We have a guide on that here https://www.linode.com/docs/applications/configuration-management/import-existing-infrastructure-to-terraform/

To prevent this situation in the future, it is suggested you use a backend for terraform. https://www.terraform.io/docs/backends/index.html

**Comment by displague** [comment]
@odra https://github.com/GoogleCloudPlatform/terraformer#use-with-linode is another option.  

Please follow-up with how this tool worked out if you choose to use it.  I'm very interested.
