### ISSUE TITLE
Change ipv4 to ip_address

### ISSUE THREAD

**Issue by golightlyb** [terraform-providers/terraform-provider-linode#67]
Hi,

The examples use the `ipv4` field of `linode_instance` resources.

This is incorrect, as this is now a set of strings. As a set, you can't index it either.

But the fix is to use `ip_address` for the `ipv4` field instead.

**Comment by golightlyb** [comment]
Also, ipv6 ends in "/64", which makes the examples error too unless you trim it:

    substr(linode_instance.foo.ipv6, 0, length(linode_instance.foo.ipv6) - 3) # trim /64

**Comment by displague** [comment]
@golightlyb Which example is using `ipv4`?

**Comment by golightlyb** [comment]
[main.tf](https://github.com/terraform-providers/terraform-provider-linode/blob/master/examples/main.tf) Ctrl+F ipv4 or ipv6

I don't know if outputs.tf is working or not

**Comment by displague** [comment]
With version `1.9.1`, after running the examples, I get:

```
$ terraform output
Nginx-Cluster = [
  "45.33.25.87",
  "45.79.47.154",
  "45.56.122.156",
]
Nginx-Lonewolf = [
  "45.79.53.88",
]
NodeBalancer-IPv4 = 45.79.61.12
NodeBalancer-IPv6 = 2600:3c00:1::2d4f:3d0c
Simple-IPv4 = 45.79.53.88/24 (li1152-88.members.linode.com)
Simple-IPv6 = 2600:3c00::f03c:92ff:fe0a:927f/64 ()
pet = tf_test_composed_trout
```

I believe examples (from the latest master branch) are doing the correct thing with the plugin at version 1.9.1:
* `ipv4` and `ipv6` is used in the examples for the Nodebalancer resources.
* `ip_address` is used for the nodes (when fetching the primary public address)
* `address` is used in the `simple_v4`/`simple_v6` data resource examples because the data resources define `address` themselves.

You are correct that an instance resource returns a list of addresses on the `ipv4` property, but the examples do not appear to be using this.

**Comment by displague** [comment]
I noticed that `linode_volume.simple-vol-lateattachment` never attached though.  It gave up after 5 minutes.  I ran subsequent applies where this attachment was the only thing the plan called for, and it would still fail after 5 minutes. (@phillc)

**Comment by golightlyb** [comment]
And the examples are setting the domains correctly too?

Bits like this from `main.cf`:

```
resource "linode_domain_record" "A-root" {
  domain_id   = linode_domain.foo-com.id
  record_type = "A"
  name        = ""
  target      = linode_nodebalancer.foo-nb.ipv4
}
```

That target just plain isn't working for me.

I can't see anything in recent changelogs that would change how this works - and the examples haven't been modified for five months regardless - but I'll try updating things and see how that goes. My terraform is only mildly out of date at v0.12.16.

**Comment by displague** [comment]
I'm wondering if you have an old version of the terraform-provider-linode plugin around (`ls -la $(which terraform-plugin-linode)`). 

Could you try running the example from a clean system/vm/container and a new git clone and see if the problems persist there?

`ipv4` in the context above is correct.  This is using the `ipv4` field from a `linode_nodebalancer`, not a `linode_instance`.

**Comment by golightlyb** [comment]
> ipv4 in the context above is correct. This is using the ipv4 field from a linode_nodebalancer, not a linode_instance

Ooooooooh!

I'm sorry, this is totally my fault.

I assumed the ipv4/ipv6 attributes on a linode_nodebalancer and a linode_instance were interchangeable. I was using the same domain examples, but applying them to instances instead of node balancers.

Thank you for your patience in diagnosing this!
